version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d:rw
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
    networks:
      - proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes:
      - vhost:/etc/nginx/vhost.d:rw
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  conf:
  vhost:
  dhparam:
  certs:

networks:
  proxy:
    external:
      name: nginx-proxy
